version: '3'

services:
  db_feed:
    image: postgres:latest
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_feed_data:/var/lib/postgresql/data/

  redis_feed:
    image: redis:latest
    ports:
      - "6379:6379"

  web_feed:
    build:
      context: .
    restart: always
    volumes:
      - .:/code
      - static-data:/vol/static
    ports:
      - "8000:8000"
    depends_on:
      - db_feed
      - redis_feed
    environment:
      DATABASE_URL: postgres://postgres:password@db_feed:5432/django_db
      REDIS_URL: redis_feed://redis_feed:6379/0

  nginx:
    image: nginx:latest
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - web_feed

volumes:
  db_feed_data:
  static-data: