# Generated by Django 5.1 on 2024-08-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
