# Generated by Django 5.1 on 2024-09-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_emailaccount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
